services:
  django:
    container_name: dj_rest
    build: .
    working_dir: /home/app/django_rest/src
    env_file:
      - ./envs/postgres.env
      - ./envs/django.env
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/home/app/django_rest/src
      - logs:/home/app/data/logs
      - csv_files:/home/app/data/csv
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    user: app

  postgres:
    container_name: dj_rest-postgres
    image: postgres:14.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./envs/postgres.env
    ports:
      - "5432:5432"

  redis:
    container_name: dj_rest-redis
    image: redis:6.2.7-alpine
    volumes:
      - redis_data:/data

  celery:
    container_name: dj_rest-celery
    build: .
    working_dir: /home/app/django_rest/src
    env_file:
      - ./envs/postgres.env
      - ./envs/django.env
    command: poetry run celery -A django_rest worker -l info
    volumes:
      - ./src:/home/app/django_rest/src
      - logs:/home/app/data/logs
      - csv_files:/home/app/data/csv
    depends_on:
      - postgres
      - redis

volumes:
  logs:
  csv_files:
  postgres_data:
  redis_data:
