# Generated by Django 3.2.14 on 2022-07-27 17:47

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('local', 'Local'), ('s3', 'S3')], default='local', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('in progress', 'In progress'), ('finished', 'Finished'), ('failed', 'Failed')], default='new', max_length=20)),
                ('result', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=10, max_digits=20), default=list, size=None)),
                ('fail_reason', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
